### ISSUE TITLE
Comments on the paper [joss.01693]

### ISSUE THREAD

**Issue by dawbarton** [LRydin/KramersMoyal#5]
Overall the paper reads well but there are a number of typos to be fixed - see the attached PDF. (There is a little to much enthusiasm for commas though.)

[10.21105.joss.01693-annotated.pdf](https://github.com/LRydin/KramersMoyal/files/3601741/10.21105.joss.01693-annotated.pdf)

**Comment by LRydin** [comment]
@dawbarton Thank you for the revisions. There are indeed a few mistakes, I will implement your corrections. The references to the figures and equations are indeed missing. I am unfamiliar with Markdown, so I wrote the paper on TeX and likely the \ref command does work on Markdown. I'll upload a corrected version of the paper to the repo. @fmeirinhos

**Comment by LRydin** [comment]
Dear @dawbarton,

I have implemented you corrections (and asked whedon to generate a new paper.pdf).
https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf

The indicated annotations you had where inserted.

There are two points I noticed and corrected simultaneously:
- The figure captions I had on my original TeX were never printed by whedon initially (given my lack of knowledge of Markdown). I have somehow found a way to introduce them in a table format. Would you be so kind to glance over the paper once more? (I'm not sure captions for figures are a standard at JOSS)
- I have come across a very relevant package for `R` that tackles similar issues of stochastic processes, that I feel should be cited in our paper, given the relevance of its content. It can calculate Kramers-Moyal coefficients in 1 and 2 dimensions (as far as I understood). It is referred to as [@Rinn2016] and the following was added: "There exists a library to retrieve Kramers--Moyal coefficents in `R` [@rinn2016]."
(https://openresearchsoftware.metajnl.com/article/10.5334/jors.123/)
[the bib.file is therefore also updated]

@kthyng I believe as an editor this information is relevant for you as well.

Best regards,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
Hi @LRydin! Some fixed for your references:

- [ ] In bibtex, author names should be separated by "and". In particular, your entry for scikitlearn needs "and" between authors instead of commas. Also your entry for Lehnertz and others. You can see examples here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
- [ ] Please also check the spacing around your references in the paper and whether they have parentheses or not. If you refer to them directly inline, they should not have parentheses. To have parentheses in your reference, use [@referencename] and to not have them, use @referencename.

**Comment by LRydin** [comment]
Dear @kthyng,

I have corrected the bib file and respectively the paper according to the two points you just mentioned. Thank you.

Best,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
Hi @LRydin, great! Still have some changes:

* 3rd paragraph, need space before reference after "... jumps in data"
* 2 "and"s in your reference called "rinn2016".

Rest looks ok but I'll read it more carefully later.

**Comment by kthyng** [comment]
It's helpful to reference the [paper review issue](https://github.com/openjournals/joss-reviews/issues/1693) from here too.

**Comment by LRydin** [comment]
Hey @kthyng,

I will attend to these right away, thank you.

Best,
Leonardo Rydin
@fmeirinhos 

P.S.: I'll refer to the paper review issue

**Comment by LRydin** [comment]
As indicated, we corrected the [above](https://github.com/LRydin/KramersMoyal/issues/5#issuecomment-543263780) comments by @kthyng 

Best,
Leonardo Rydin
@fmeirinhos 
Referring the [review issue](https://github.com/openjournals/joss-reviews/issues/1693)

**Comment by kthyng** [comment]
looking good!

**Comment by kthyng** [comment]
@dawbarton Is this issue ready to be closed from your perspective?

**Comment by dawbarton** [comment]
Yes, looks good to me.
